### PR TITLE
fix(createHoc): don't copy defaultProps from wrapped component

### LINKED ISSUE #152: If innerComponent has `defaultProps.classes`, they override `classes` injected by HOC
I don't really understand why the HOC copies over so much stuff like `defaultProps` and `contextTypes` from the wrapped component instead of just creating a standalone component that renders the wrapped one.  If I have

```js
class MyComp extends React.Component {
  static defaultProps = {
    classes: {
      root: 'MyComp-root',
    }
  }
}

const styles = {
  root: {},
}

export default injectSheet(styles)(MyComp)
```

The created HOC doesn't work because it takes on the `defaultProps` from `MyComp`, so the rendered `classes.root` is always `'MyComp-root'`. 💥 💣

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #152

### CODE REVIEW

**Comment by kof** [comment]
That line was there for  a reason)

**Comment by kof** [comment]
Thanks for the PR, closing this in favor of https://github.com/cssinjs/react-jss/issues/132

**Comment by jedwards1211** [comment]
What was the reason?  It's the kind of thing where my initial prejudice is whatever that reason might be, I believe there has to be a better way to do it

**Comment by kof** [comment]
Do you have another use case in mind that demonstrates its not a good idea to forward default props to the HOC? Imagine classes merge is already fixed.

**Comment by jedwards1211** [comment]
Yes, creating a library component that users can use with plain CSS or with JSS:

`CircularProgress.js`
```js
export default class CircularProgress extends React.Component {
  static defaultProps = {
    // class names for when the user is importing a CSS file -
    // if the user wraps this with `injectSheet`, these should not get used.
    classes: {
      root: 'CircularProgress-root',
      track: 'CircularProgress-track',
      ...
    }
  }
}
export const jssStyles = {
  root: {
    ...
  },
  track: {
    backgroundColor: '#eeeeee',
  },
}
```

`CircularProgress.css`
```css
.CircularProgress-root {
  ...
}
.CircularProgress-track {
  background-color: #eeeeee;
}
```

`CircularProgress-jss-styles.js`
```js

```

Usage with CSS
```js
import 'react-circular-progressbar/CircularProgress.css'
import CircularProgress from 'react-circular-progressbar'
```

Usage with JSS
```js
import BaseCircularProgress, {jssStyles} from 'react-circular-progressbar'
import injectSheet from 'react-jss'
const CircularProgress = injectSheet(jssStyles)(BaseCircularProgress)
```

**Comment by jedwards1211** [comment]
Hang on, the example I posted was not very good...

**Comment by jedwards1211** [comment]
Okay, imagine you want to create a `Panel` component that uses Bootstrap's panel classes by default.  But if you want to style it differently, you can pass your own `classes` prop to it and it will use those instead of Bootstrap CSS.

```js
const Panel = ({classes, header, footer, children}) => (
  <div className={classes.panel}>
    {header && <div className={classes.header}>{header}</div>}
    {children && <div className={classes.body}>{children}</div>}
    {footer && <div className={classes.footer}>{footer}</div>}
  </div>
)
Panel.defaultProps = {
  classes: {
    panel: 'panel',
    header: 'panel-header',
    body: 'panel-body',
    footer: 'panel-footer',
  }
}

<Panel header={<h4>Bootstrap Panel</h4>}>Body</Panel>

const styles = {
  panel: {...},
  header: {...},
  body: {...},
  footer: {...},
}
const CustomPanel = injectSheet(styles)(Panel)

<CustomPanel header={<h4>Custom Panel</h4>}>Body</CustomPanel>
```

So `<Panel>` above should render
```jsx
<div className="panel">
  <div className="panel-header">
    <h4>Bootstrap Panel</h4>
  </div>
  <div className="panel-body">
     Body
  </div>
</div>
```

And `<CustomPanel>` above should render something like (I forget how the numbering works):
```jsx
<div className="panel-0-0">
  <div className="header-0-1">
    <h4>Bootstrap Panel</h4>
  </div>
  <div className="body-0-2">
     Body
  </div>
</div>
```

But with `defaultProps.classes` getting merged in, we'd get Bootstrap styles clashing with the injected ones:
```jsx
<div className="panel panel-0-0">
  <div className="panel-header header-0-1">
    <h4>Bootstrap Panel</h4>
  </div>
  <div className="panel-body body-0-2">
     Body
  </div>
</div>
```

**Comment by kof** [comment]
Is that scenario realistic?

**Comment by kof** [comment]
@oliviertassinari wdyt?

**Comment by jedwards1211** [comment]
@kof somewhat.  Here's another question though: why should rendering an instance of an `injectSheet(styles)(Panel)` behave any differently than rendering `<Panel classes={{panel: 'panel-0-0', header: 'header-0-1', ...}} />`

**Comment by oliviertassinari** [comment]
I don't follow, this PR looks great.

**Comment by oliviertassinari** [comment]
Also, I would add [hoist-non-react-statics](https://github.com/mridgway/hoist-non-react-statics)

**Comment by kof** [comment]
@oliviertassinari this is already in place.

**Comment by jedwards1211** [comment]
In any case, if `defaultProps` aren't automatically copied, it gives people more flexibility, since they still have the option of copying over `defaultProps` manually if they want

**Comment by kof** [comment]
PR is not good, because there is a failing test. I am looking into it.

**Comment by kof** [comment]
Now as I looked into the failing test, the reason was a different one. It is the passing props object to a function value. It was basically an easy way to do it, because I just reference it and react does the merge, but now I see that it is actually wrong and needs fixing.

**Comment by jedwards1211** [comment]
@kof this does re-break what @kserjey expected in https://github.com/cssinjs/react-jss/issues/87
But, over there I argue that `injectSheet` should be working like `react-redux` and #87 shouldn't be considered a bug.

**Pull request closed without merging**
