### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by cvle**

### CODE REVIEW

**Comment by kof** [comment]
Can we somehow indicate the coverage on the readme with a badge?

**Comment by kof** [comment]
Initially I was thinking to use codecov.io because it gives you a badge and also shows coverage stats on each PR…

**Comment by cvle** [comment]
I personally use coveralls.io. I think it offers the same features but I haven't been using the PR feature yet.

**Comment by cvle** [comment]
With this PR we have the coverage information after running test, we then need to send it to the codecov service. Normally I send coverage information using travis, but we don't have travis setup for the plugins. If we want PRs to show coverage stats, we will need travis to setup here too.

**Comment by kof** [comment]
We need to setup travis anyways. So you think we still can use codecov or coveralls with this setup? If yes then lets merge this first and do those things later.

**Comment by cvle** [comment]
Exactly. With this PR all you need to do is to run the test and use the CLI from codecov / coveralls.

**Pull request merged**
