### PR TITLE
Fixes manager for SSR

### PR DESCRIPTION
**Pull request by kof**
Fixes (1) in #133

### CODE REVIEW

**Comment by kof** [comment]
cc @oliviertassinari

**Comment by oliviertassinari** [comment]
@kof I'm not sure my feedback is relevant here. I have been adopting a different solution to handle style deduplication on Material-UI: the `sheetManager` is a simple `Map`.

**Comment by kof** [comment]
I am assuming you can switch step by step to use react-jss as is in the future. So it is important that I don't do anything that mui can't use.

**Comment by kof** [comment]
We have a more complex scenario because of theming and dynamic styles.

**Comment by oliviertassinari** [comment]
@kof Oh, then we need to discuss this sheetManager further on gitter. This is the part I had to do the most changes. I don't think that the current implementation will satisfies Material-UI needs.

**Comment by kof** [comment]
Alright, now #157 is also implemented.

**Comment by kof** [comment]
Ok, this one seems ready

**Pull request merged**
