### PR TITLE
Next

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by a-ignatov-parc** [comment]
Good morning!

I've updated `react-jss` to `7.0.0-pre` in order to fix SSR issue. And I still have problem with non deterministic id generation

```js
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ZVGHOE3Wc default-0-3 default-0-0 _1rtjm
 (server) ZVGHOE3Wc default-0-0 default-0-0 _1rtjm
```

This warning happened with only one styled with jss component placed on the page.

Is there any information I can provide to help fix this problem?

**Comment by kof** [comment]
Yes, please create a reproducible example

**Comment by a-ignatov-parc** [comment]
I think the problem is in [this line](https://github.com/cssinjs/react-jss/blob/next/src/createHoc.js#L75-L77). Options passed to `createStyleSheet` during SSR contains custom `generateClassName` that is why my dynamic styles has `ruleCounter` equal to `0` and the result is `default-0-0 default-0-0`. But in browser it uses global generator with result `default-0-3 default-0-0`

If I'm wrong I'll try to create example closer to weekends. 

P.S. Styles used in my component are

```jsx
function primaryColor({ theme }) {
  return theme.colors.primary;
}

function secondaryColor({ theme }) {
  return theme.colors.secondary;
}

function textColor({ theme }) {
  return theme.colors.text;
}

function alphaColor(value = 1) {
  return colorResolver => props => {
    const resolvedColor = colorResolver(props).toString();
    return color(resolvedColor)
      .alpha(value)
      .string();
  };
}

const themedStyles = {
  default: {
    color: primaryColor,
    '&:hover': { color: textColor },
    '&:active': { color: textColor },
    '&:visited': { color: alphaColor(0.8)(primaryColor) },
  },
  secondary: {
    color: secondaryColor,
    '&:hover': { color: primaryColor },
    '&:active': { color: primaryColor },
    '&:visited': { color: alphaColor(0.8)(secondaryColor) },
  },
  native: {
    color: textColor,
    '&:hover': { color: primaryColor },
    '&:active': { color: primaryColor },
    '&:visited': { color: alphaColor(0.8)(primaryColor) },
  },
};
```

`theme` is custom prop not related to `ThemeProvider`.

**Comment by a-ignatov-parc** [comment]
Additional info about id generation.

server
```jsx
'default' 0 0
'secondary' 0 1
'native' 0 2
'.default-0-0:hover' 0 3
'.default-0-0:active' 0 4
'.default-0-0:visited' 0 5
'.secondary-0-1:hover' 0 6
'.secondary-0-1:active' 0 7
'.secondary-0-1:visited' 0 8
'.native-0-2:hover' 0 9
'.native-0-2:active' 0 10
'.native-0-2:visited' 0 11
```

client
```jsx
"default" 0 0
"secondary" 0 1
"native" 0 2
"default" 0 3
"secondary" 0 4
"native" 0 5
".default-0-0:hover" 0 6
".default-0-0:active" 0 7
".default-0-0:visited" 0 8
".secondary-0-1:hover" 0 9
".secondary-0-1:active" 0 10
".secondary-0-1:visited" 0 11
".native-0-2:hover" 0 12
".native-0-2:active" 0 13
".native-0-2:visited" 0 14
```

This logs are from `createGenerateClassName`

**Comment by kof** [comment]
Any chance you can give me a reproducible WORKING example?

**Comment by a-ignatov-parc** [comment]
Sure. But I need more time to do this.

**Comment by a-ignatov-parc** [comment]
I think I have figured out test case. 

I have two renders on the server. One for data resolving and another is for actual render with resolved data (I use [react-resolver](https://github.com/ericclemmons/react-resolver)). And because of this [line](https://github.com/cssinjs/react-jss/blob/50f3822a95f09cff920dc4cb090e51099a140ca1/src/createHoc.js#L43) on second render styles generated differently (as showed in my previous comment). If I disable that statement rendering starts to work as expected.

I think [`staticSheet` and `dynamicStyles`](https://github.com/cssinjs/react-jss/blob/50f3822a95f09cff920dc4cb090e51099a140ca1/src/createHoc.js#L44-L45) should regenerate on every request on server side.

Additional [debug info](https://gist.github.com/a-ignatov-parc/3415ddf858eac460b23b931ef76da3e8).

P.S. I will provide example app but it'll take some time to create it. Sorry...

**Comment by kof** [comment]
> I think staticSheet and dynamicStyles should regenerate on every request on server side.

def. true, I will try to create a failing test soon.

**Comment by kof** [comment]
While I was trying to reproduce this, I found another bug and fixed it, it is published as react-jss@7.0.0-pre.1, try this one.

**Comment by kof** [comment]
I really need your rendering code to see whats going on.

**Comment by kof** [comment]
> I think staticSheet and dynamicStyles should regenerate on every request on server side.

On the second thought, why would they need to regenerate on each request if they are not changed? Dynamic sheet just needs an update.

**Comment by a-ignatov-parc** [comment]
> On the second thought, why would they need to regenerate on each request if they are not changed? That would be a waste of ressources. Dynamic sheet just needs an update.

The problem that I detected was related to node modules singleton nature + closures used with `staticSheet` in `createHoc`.

Here is simple example component

```jsx
function Link() {
    ...
}

export default injectStyles(themedStyles)(Link);
```

On first request you are caching styles with [this line](https://github.com/cssinjs/react-jss/blob/50f3822a95f09cff920dc4cb090e51099a140ca1/src/createHoc.js#L44-L45) and then incrementing some counters (`refNs`) + attaching styles.

On second request [this line](https://github.com/cssinjs/react-jss/blob/50f3822a95f09cff920dc4cb090e51099a140ca1/src/createHoc.js#L44-L45) won't execute because `staticSheet` is already saved in upper scope upon prev request and I think this is root cause for wrong style resolution.

P.S. I will check you fix soon and let you know the results ;)
P.P.S. I understand that example will significantly help you but my project is private at this moment and have complex runtime so it's almost impossible to share it with you. I need to create test case from the scratch and that might take a while.

**Comment by a-ignatov-parc** [comment]
`7.0.0-pre.1` didn't fix my problem but i've come to solution that works properly in all of my cases. I'll make PR in few hours.

**Comment by kof** [comment]
Please do it with a test

**Comment by a-ignatov-parc** [comment]
> Please do it with a test

Already working on it

P.S. here is my PR https://github.com/cssinjs/react-jss/pull/107

**Comment by a-ignatov-parc** [comment]
@kof added test cases in https://github.com/cssinjs/react-jss/pull/107

**Comment by iamstarkov** [comment]
published this branch.

use it either:
* by directly referencing to prerelease version: `react-jss@7.0.0-pre.2`
* or referencing to `next` dist-tag: `react-jss@next`

changed `latest` dist-tag to 6.1.1, so npm will show relevant README, and people want use pre-release versions unintentionally

**Comment by a-ignatov-parc** [comment]
Checked `7.0.0-pre.2`. Now SSR works great 👍

**Comment by iamstarkov** [comment]
@a-ignatov-parc nice

**Comment by iamstarkov** [comment]
hot reload works as well, verified in https://github.com/iamstarkov/react-jss-next-demo (`clone`, `npm install` and `npm run dev` it and then change anything, related to either)

**Comment by kof** [comment]
nice

**Comment by kof** [comment]
I just fucking merged that!

**Pull request merged**
